### ISSUE TITLE
Optimize MDN database query to handle more traffic

### ISSUE THREAD

**Issue by safwanrahman** [mozmeao/infra#677] opened 2017-12-08 15:25 UTC
Some of the sql query of kuma is not optimized. Need to investigate and find out if its possible to optimize the query inorder to handle more traffic with the current infrastructure.

**Comment by jwhitlock** [comment] 2017-12-18 22:32
In a recent event, the most time consuming processes were:

* ``kuma.wiki.views.document:document`` - 74% of the time, about 2000 requests per minute. 60% was spent in MySQL, 12% rendering the page, and 9% in Memcache.
* ``kuma.wiki.middleware:DocumentZoneMiddleware`` - 17% of the time, about 50 requests per minute. 50% was spent in Memcache, 22% in database, and 20% reporting an error to Sentry.

This suggests to me that it is the volume of requests that is the issue, and that a momentary Memcache slowdown lead to downtime.

I've been staring at similar numbers for previous downtimes, and I've come to the conclusion that the issue isn't database query performance, but that normal "weather" events in AWS combined with high external traffic are causing the issues. We can insulate the users from these events by serving more traffic from cached pages in a CDN.

However, there's nothing wrong with more efficient database queries as well. Take a look at ``kuma.wiki.views.document:document`` and the homepage (used to tell if the site is up) for query efficency gains.

**Comment by safwanrahman** [comment] 2018-01-03 20:22
@jwhitlock I got your point.
For some curious purpose, is it possible to share last 5 incident report so I can investigate more what affects the site actually?

**Comment by jwhitlock** [comment] 2018-01-03 20:41
I've shared recent incident reports, since @safwanrahman is under NDA.

**Comment by safwanrahman** [comment] 2018-01-31 18:04
As https://github.com/mozilla/kuma/pull/4630 has been deployed at 29th January, we have seen some improvements in the response time! as you can see in the following chart. The line is the timeframe when the Patch has been deployed. As you can see, the spike goes down heavily. 😃 
![image](https://user-images.githubusercontent.com/7114151/35638762-37d0e8f0-06e2-11e8-9755-81e810dd4cd1.png)

There are more a lot of space for optimization, like the revision page as well as document list page. In the future, I will investigate the possible ways to serve the pages more optmizely, and implement my findings.

**Comment by metadave** [comment] 2018-01-31 19:11
this is excellent @safwanrahman, thanks so much for your awesome efforts!!

**Comment by jwhitlock** [comment] 2018-05-24 15:15
Closing, since the infrastructure issue appears to be under control.

**Closed by jwhitlock** 2018-05-24 15:15 UTC
Labels: MDN, analysis
