### ISSUE TITLE
plan memcached/redis queue migration for go-live

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#402] opened 2017-08-08 18:45 UTC
@escattone you mentioned that there could be up to ~60k objects in one (or both?) of the queues when the site is busy, is this data that we have to migrate when we go live?

**Comment by escattone** [comment] 2017-08-08 20:07
@metadave That's a good question. There are five queues that are used:
- `mdn_purgeable`
- `mdn_search`
- `mdn_emails`
- `mdn_wiki`
- `celery`

There is no need to migrate the `mdn_purgeable` queue, but I think it would be best if the others were migrated. I have no idea how to do that though. However, for the maintenance-mode production test, we don't have to migrate anything, since the `Celery` task system is not used during maintenance mode.

**Comment by metadave** [comment] 2017-08-08 20:12
@escattone is it possible that we just turn off the app, wait for all the queues to clear, and then cut over when prod goes live? I'm not sure how long this would take, or if a few minutes of downtime is acceptable.

**Comment by escattone** [comment] 2017-08-08 20:15
@metadave That's a good idea. Perhaps we can put MDN on SCL3 in maintenance mode until the queues drain, then cut over to the AWS MDN.

**Comment by jwhitlock** [comment] 2017-08-09 23:40
I'm a fan of draining the queues. I've never tried moving tasks from one backend to another.

**Comment by metadave** [comment] 2017-08-11 13:11
if we cutover on a weekend, how many objects would you estimate there being in all the queues, or how long would it take these queues to drain?

**Comment by escattone** [comment] 2017-08-11 23:55
@metadave Yes, some of the tasks in some of the queues do affect data in MySQL. I'm thinking that we'll have to do the following, in order:

1. put the SCL3 MDN in maintenance-mode (by deploying MDN with MAINTENANCE_MODE=True)
2. wait for the queues to drain
3. perform a MySQL dump
4. load the MySQL dump into the prod AWS RDS instance
5. load an anonymized version of the MySQL dump into the stage AWS RDS instance?
5. make sure all of the attachments and legacy files (diagrams/presentations/samples) have been sync'ed from SCL3 to the dev, stage and prod EFS instances
5. deploy stage and prod MDN on K8s cluster(s)
6. flip the stage and prod DNS switches

Does that make sense? I've probably missed something.

**Comment by metadave** [comment] 2017-08-14 14:21
@escattone excellent, I've started some rough notes on what will eventually be the release plan [here](https://github.com/mozmeao/infra/issues/409).

**Comment by jwhitlock** [comment] 2017-08-17 14:38
I can't recall if we've tested maintenance mode in SCL3. That's an additional task if we're running it there, and it may be non-trivial to get it working, requiring WebOps assistance to update puppet-controlled files or pushing an alternate branch.  I don't think it's needed.  In general, celery chews through the task queue in less than 10 seconds, and we just need to ensure new tasks are not being added.

We can shutdown ``celerybeat``, which will stop adding new periodic tasks, and move traffic to maintenance mode in AWS, which will stop queuing cacheback tasks.

**Comment by jwhitlock** [comment] 2017-09-09 20:44
@escattone confirmed that he has tested maintenance mode in SCL3 staging, by updating the Kuma settings and pushing a new branch, without WebOps assistance. A similar process can be used to set SCL3 staging and production to maintenance mode. The consensus was that prod SCL3 as the maintenance mode server was the least schedule risk for going live.

Being in maintenance mode will avoid the "important" celery tasks, like sending first edit emails and edit notification emails, because you won't be able to do the tasks like editing pages. Background rendering tasks will also be "null tasks" in maintenance mode.

If the SCL3 production server is serving maintenance mode traffic, then cacheback tasks will continue to be queued, and will need to be processed by celery workers.  Render tasks will also be queued, and workers will need to "process" them to avoid filling up the queues. However, we can stop the periodic scheduled tasks (``celerybeat``) and task writes to the database (``celerycam``) by shutting down the services during maintenance mode.

Here's the process:

* Put SCL3 prod in maintenance mode
* As root on developer-celery1, ``supervisorctl stop celerybeat celerycam``
* Stop replication and take the database backup

**Comment by jwhitlock** [comment] 2017-09-20 18:30
We tested maintenance mode (MM) on developer.mozilla.org today. ``celerybeat`` failed to start due to file permission errors. If it is easy, we'll fix it, but the plan is to manually stop the service.

``celery`` continued to process cacheback tasks during MM. I think it is OK to lose these in the transition. We're not transferring the cache contents, so AWS will need to redo the work anyway.  We may have spiky cacheback workloads in the first month of AWS, some of which may require some intervention.  We'll know more about this after sending some traffic to AWS in MM mode.

I think we have the 95% plan for memcached/redis queue migration, so I'm closing the issue. Please re-open if you think more discussion is needed.

**Closed by jwhitlock** 2017-09-20 18:30 UTC
Labels: MDN, planning
